Repository videojs/video.js, pull requests merged in 2018-04, with the labels that each got.

#4861 fix: let the tech preload auto on its own
  src/js/player.js
  test/unit/sourceset.test.js
Labels: sourceset

#5061 Feature/queue playback events for zero playback rate (vjs6)
  src/js/player.js
  src/js/tech/tech.js
  test/unit/player.test.js
  test/unit/tech/tech.test.js
Labels: 6.x

#5093 fix: init inactivity checker not until first play event
  src/js/player.js
  test/unit/player.test.js
Labels: confirmed

#5097 Moving seekbar event handler bindings into a function
  src/js/control-bar/progress-control/seek-bar.js
Labels: confirmed

#5074 Add option to override native audio and video to html5 tech
  src/js/tech/html5.js
  src/js/tech/tech.js
  test/unit/tech/html5.test.js
Labels: confirmed, major

#5107 Fix overrideNative flag(s) in IE11
  src/js/tech/html5.js
  src/js/tech/tech.js
  test/unit/tech/html5.test.js
Labels: needs: LGTM
