Repository videojs/video.js, pull requests merged in 2018-11, with the labels that each got.

#5463 fix: adds correct cursor pointer for the play/pause controlbar button.
  src/css/components/_play-pause.scss
Labels: confirmed

#5465 fix: vjs-lock-showing class gets removed from menu when no longer hovering on menu-button.
  src/js/menu/menu-button.js
  src/js/menu/menu.js
Labels: a11y, confirmed

#5578 [i18n] Add the Occitan locale
  lang/oc.json
Labels: i18n
