Repository videojs/video.js, pull requests merged in 2018-03, with the labels that each got.

#4986 fix: Fix an issue where disabling the progress control would throw an error.
  src/js/control-bar/progress-control/seek-bar.js
Labels: confirmed, patch

#4974 Small addition to an if check to fix an error
  src/js/tracks/text-track-display.js
Labels: needs: LGTM, patch

#4660 feat: sourceset
  src/js/player.js
  src/js/tech/html5.js
  src/js/tech/tech.js
  test/unit/sourceset.test.js
  test/unit/tech/html5.test.js
Labels: confirmed, minor

#4921 Allow techs to change poster if player option `techCanOverridePoster` is set
  docs/guides/options.md
  docs/guides/tech.md
  src/js/player.js
  test/unit/player.test.js
  test/unit/tech/tech-faker.js
Labels: confirmed, minor

#4947 feat: add mimetype type to source object when possible (#4469)
  src/js/utils/filter-source.js
  src/js/utils/mimetypes.js
  test/unit/utils/filter-source.test.js
Labels: confirmed, minor

#4962 feat: Add an option to override format-time (#2931)
  src/js/utils/format-time.js
  src/js/video.js
  test/unit/utils/format-time.test.js
Labels: confirmed, minor

#5002 fix: remove CaptionsSettingsMenuItem when TextTrackSetting is not inc…
  src/js/control-bar/text-track-controls/captions-button.js
  src/js/control-bar/text-track-controls/subs-caps-button.js
  test/unit/tracks/text-track-settings.test.js
Labels: confirmed, patch

#5008 Fix misspellings
  src/js/utils/dom.js
Labels: confirmed, patch

#4997 Use CSS grid for caption Setting overlay to avoid cutoff
  src/css/components/_captions-settings.scss
Labels: minor, needs: LGTM

#5022 test(ResizeManager): only listen for one playerresize to make test not flaky
  test/unit/resize-manager.test.js
Labels: confirmed, patch

#5016 fix(sourceset): set evt.src to empty string or src attr from load
  src/js/player.js
  src/js/tech/html5.js
  test/karma.conf.js
  test/unit/sourceset.test.js
Labels: needs: LGTM, patch

#5037 refactor: move sourceset code out of tech
  src/js/tech/html5.js
  src/js/tech/setup-sourceset.js
Labels: sourceset

#5049 6.x refactor: move sourceset code out of tech
  src/js/tech/html5.js
  src/js/tech/setup-sourceset.js
Labels: sourceset
