Repository videojs/video.js, pull requests merged in 2018-05, with the labels that each got.

#5040 feat: update the players source cache on sourceset
  src/js/player.js
  src/js/utils/filter-source.js
  src/js/utils/mimetypes.js
  test/unit/sourceset.test.js
Labels: confirmed, sourceset

#5156 feat(6.x): update the players source cache on sourceset (#5040)
  src/js/player.js
  src/js/utils/filter-source.js
  src/js/utils/mimetypes.js
  test/unit/sourceset.test.js
Labels: 6.x

#5054 fix: several source setting inconsistencies and slight refactor
  src/js/player.js
  src/js/tech/html5.js
  src/js/tech/setup-sourceset.js
  src/js/utils/filter-source.js
  test/unit/sourceset.test.js
Labels: confirmed, sourceset

#5039 Fix: `video-js` el sourceset
  src/js/player.js
  test/unit/sourceset.test.js
Labels: confirmed, sourceset

#5163 feat: copy properties from <video-js> to the media el (#5039)
  src/js/player.js
  test/unit/sourceset.test.js
Labels: 6.x, sourceset

#5123 feat: add 'autoSetup' option
  docs/guides/options.md
  src/js/setup.js
Labels: confirmed

#5153 Fix IDs and ARIA attributes in Captions Settings Dialog
  src/js/tracks/text-track-settings.js
Labels: 6.x, a11y, confirmed

#5154 Remove unnecessary ARIA role on the Control Bar. Fixes #5134
  src/js/control-bar/control-bar.js
Labels: 6.x, a11y, confirmed

#5157 Fix time-display.js to restore hidden label text for screen readers. Fixes #5135
  docs/guides/languages.md
  docs/legacy-docs/guides/languages.html
  docs/translations-needed.md
  lang/ar.json
  lang/ba.json
  lang/bg.json
  lang/ca.json
  lang/cs.json
  lang/da.json
  lang/de.json
  lang/el.json
  lang/en.json
  lang/es.json
  lang/fa.json
  lang/fi.json
  lang/fr.json
  lang/gl.json
  lang/he.json
  lang/hr.json
  lang/hu.json
  lang/it.json
  lang/ja.json
  lang/ko.json
  lang/nb.json
  lang/nl.json
  lang/nn.json
  lang/pl.json
  lang/pt-BR.json
  lang/pt-PT.json
  lang/ru.json
  lang/sk.json
  lang/sr.json
  lang/sv.json
  lang/tr.json
  lang/uk.json
  lang/vi.json
  lang/zh-CN.json
  lang/zh-TW.json
  sandbox/language.html.example
  src/js/control-bar/live-display.js
  src/js/control-bar/time-controls/current-time-display.js
  src/js/control-bar/time-controls/duration-display.js
  src/js/control-bar/time-controls/remaining-time-display.js
  src/js/control-bar/time-controls/time-display.js
Labels: 6.x, a11y, confirmed

#5158 Reduce the multiple-announcement by screen readers of the new name of a button when its text label changes. Partial fix to #5023
  src/js/button.js
  src/js/clickable-component.js
  test/unit/button.test.js
Labels: 6.x, a11y, confirmed

#5162 fix: `sourceset` and browser behavior inconsistencies (#5054)
  src/js/player.js
  src/js/tech/html5.js
  src/js/tech/setup-sourceset.js
  src/js/utils/filter-source.js
  test/unit/sourceset.test.js
Labels: 6.x, sourceset

#5177 fix/sourceset el check
  src/js/tech/html5.js
Labels: 6.x, confirmed

#5180 tests: do not throw on tech/player dispose
  src/js/resize-manager.js
  test/unit/player.test.js
Labels: 6.x

#5192 Remove IE9 text track HTML markup in the doc/examples, and update to use video.js v7.0
  README.md
  docs/examples/elephantsdream/index.html
  docs/examples/simple-embed/index.html
Labels: confirmed

#5173 Workaround for #4583 (JAWS+IE doesn't announce BPB or play button)
  src/js/player.js
Labels: a11y, confirmed, screen reader bug

#5171 Change menu items to ARIA role of "menuitemradio" when only one item can be selected
  src/js/control-bar/audio-track-controls/audio-track-button.js
  src/js/control-bar/playback-rate-menu/playback-rate-menu-item.js
  src/js/control-bar/text-track-controls/chapters-track-menu-item.js
  src/js/control-bar/text-track-controls/off-text-track-menu-item.js
  src/js/control-bar/text-track-controls/text-track-button.js
  src/js/menu/menu-item.js
Labels: a11y, confirmed

#5201 Clarify how to Land a PR using the GitHub UI
  COLLABORATOR_GUIDE.md
Labels: confirmed
