Repository videojs/video.js, pull requests merged in 2018-12, with the labels that each got.

#5673 Improve sv.json file
  lang/sv.json
Labels: patch

#5653 fix: current time and duration display accessibility with VoiceOver
  src/js/control-bar/time-controls/time-display.js
  src/js/control-bar/time-controls/time-divider.js
Labels: patch

#5655 Fix hidden Control Text in Progress bar (Fixes #5251)
  src/js/control-bar/progress-control/load-progress-bar.js
  src/js/control-bar/progress-control/play-progress-bar.js
  src/js/control-bar/progress-control/time-tooltip.js
Labels: a11y, patch

#5670 test: add a test to check various children set to false
  package-lock.json
  src/js/control-bar/progress-control/load-progress-bar.js
  src/js/control-bar/progress-control/seek-bar.js
  src/js/control-bar/progress-control/time-tooltip.js
  src/js/control-bar/seek-to-live.js
  src/js/player.js
  test/unit/controls.test.js
  test/unit/player.test.js
Labels: patch

#5651 fix: make seek-to-live accessible
  docs/translations-needed.md
  lang/en.json
  src/css/components/_live.scss
  src/js/control-bar/seek-to-live.js
Labels: patch

#5692 fix: Control-bar autohide when cursor placed over it #5258
  src/js/player.js
  test/unit/player.test.js
Labels: confirmed, patch

#5687 Fix css animation order
  src/css/components/_loading.scss
Labels: confirmed, patch
