Repository videojs/video.js, pull requests merged in 2018-06, with the labels that each got.

#5219 fix: suppress console warnings in Chrome on mobile when scrubbing progress slider
  src/css/components/_progress.scss
  src/js/slider/slider.js
Labels: confirmed, tested

#5249 Add zip file to npmignore
  .npmignore
Labels: confirmed

#5255 fix: Allow evented objects, such as components and plugins, to listen to the window object in addition to DOM objects.
  src/js/mixins/evented.js
  test/unit/mixins/evented.test.js
Labels: confirmed

#5239 feat: run autoprefixer on css
  build/grunt.js
  package-lock.json
  package.json
  postcss.config.js
Labels: confirmed

#5209 feat: manual autoplay
  docs/guides/faq.md
  docs/guides/options.md
  src/js/player.js
  test/unit/autoplay.test.js
  test/unit/tech/tech-faker.js
Labels: confirmed

#5052 feat: show mute toggle button if the tech supports muting volume
  src/css/components/_volume.scss
  src/js/control-bar/mute-toggle.js
  src/js/control-bar/volume-control/check-mute-support.js
  src/js/control-bar/volume-panel.js
  src/js/tech/html5.js
  src/js/tech/tech.js
  test/unit/controls.test.js
Labels: confirmed

#4599 Add an Audio Description icon to an audio track name in the track menu if it is "main-desc" kind.
  src/css/components/_audio.scss
  src/js/control-bar/audio-track-controls/audio-track-menu-item.js
Labels: a11y, confirmed, minor
