Repository videojs/video.js, pull requests merged in 2018-02, with the labels that each got.

#4920 Only select TextTrackMenuItem if unselected
  src/js/control-bar/text-track-controls/off-text-track-menu-item.js
  src/js/control-bar/text-track-controls/text-track-menu-item.js
  src/js/menu/menu-item.js
Labels: confirmed, patch

#4939 fix: cache middleware instances per player
  src/js/player.js
  src/js/tech/middleware.js
  test/unit/tech/middleware.test.js
Labels: confirmed, patch

#4918 Fix the video continue player when user drag in timeline
  src/js/control-bar/progress-control/progress-control.js
  src/js/control-bar/progress-control/seek-bar.js
Labels: confirmed, patch

#4926 docs(middleware): updating the middleware guide with setTech and other corrections
  docs/guides/middleware.md
Labels: documentation, needs: LGTM, patch

#4955 chore(package): update to videojs-vtt.js 0.12.6
  .nvmrc
  package.json
Labels: 5.x

#4916 fix: Add alternate text in an ARIA alert to the loading spinner.
  docs/translations-needed.md
  lang/en.json
  src/js/loading-spinner.js
Labels: a11y
