Repository videojs/video.js, pull requests merged in 2019-01, with the labels that each got.

#5652 feat: Add loadMedia and getMedia methods
  src/js/player.js
  src/js/utils/mimetypes.js
  test/unit/player-loadmedia.test.js
  test/unit/player.test.js
Labels: confirmed, minor

#5663 Add touch supported class for touch supporting devices
  src/js/player.js
  test/unit/player.test.js
Labels: confirmed, minor

#5676 fix: make sure sources, volume, and playback rate are reset along with the player
  src/js/player.js
  test/unit/player.test.js
  test/unit/tech/tech-faker.js
Labels: patch

#5671 Move the "-" in remaining-time-display.js so it is not announced by screen readers. Fixes #5168
  src/js/control-bar/time-controls/remaining-time-display.js
  src/js/control-bar/time-controls/time-display.js
  src/js/utils/fn.js
  src/js/utils/url.js
Labels: a11y, patch

#5686 fix(fs): make sure there's only one fullscreenchange event
  src/js/fullscreen-api.js
  src/js/player.js
Labels: needs: LGTM, patch

#5721 fix(seekbar): don't disable if live tracker's seekable is infinity
  src/js/control-bar/progress-control/seek-bar.js
Labels: patch

#5702 fix: remove child from old parent when moving to new parent via addChild
  src/js/component.js
  test/unit/component.test.js
  test/unit/menu.test.js
Labels: patch

#5684 Feature/reset player ui #4683
  src/js/control-bar/time-controls/remaining-time-display.js
  src/js/player.js
  test/unit/player.test.js
  test/unit/reset-ui.test.js
Labels: patch

#5756 fix(fs): fix double fullscreenchange event
  src/js/fullscreen-api.js
  src/js/player.js
Labels: needs: LGTM

#5754 [A11y Fix] - Ensure resizeManager is not focusable via tab
  src/js/resize-manager.js
  test/unit/resize-manager.test.js
Labels: a11y

#5571 Extend SeekBar keyboard handling, and support hotkeys "m", "f", "k" and Space
  docs/guides/options.md
  package-lock.json
  package.json
  rollup.config.js
  sandbox/hotkeys.html.example
  src/js/big-play-button.js
  src/js/button.js
  src/js/clickable-component.js
  src/js/close-button.js
  src/js/component.js
  src/js/control-bar/progress-control/seek-bar.js
  src/js/menu/menu-button.js
  src/js/menu/menu-item.js
  src/js/menu/menu-keys.js
  src/js/menu/menu.js
  src/js/modal-dialog.js
  src/js/player.js
  src/js/poster-image.js
  src/js/slider/slider.js
Labels: minor

#5611 Feat(player): add option to disable or override double-click handling. Fixes #5604
  docs/guides/options.md
  src/js/player.js
Labels: minor
