Repository videojs/video.js, pull requests merged in 2019-06, with the labels that each got.

#6001 Add Picture-in-Picture API methods
  src/js/player.js
  src/js/tech/html5.js
  src/js/tech/tech.js
  test/api/api.js
Labels: needs: LGTM

#5977 feat: any event function
  src/js/event-target.js
  src/js/mixins/evented.js
  src/js/utils/events.js
  test/unit/events.test.js
  test/unit/mixins/evented.test.js
Labels: tested

#5856 feat(fs): support FullscreenOptions
  docs/guides/options.md
  src/js/control-bar/fullscreen-toggle.js
  src/js/fullscreen-api.js
  src/js/player.js
  test/unit/player-fullscreen.test.js
Labels: confirmed

#5803 Fix polymer issue by marking click event with stopPropagation
  src/js/control-bar/play-toggle.js
Labels: confirmed, tested

#6050 Close button supports Esc key pressed
  src/js/close-button.js
  test/unit/close-button.test.js
Labels: confirmed, tested

#6021 Introduce write method to handle value output
  src/js/control-bar/progress-control/time-tooltip.js
Labels: confirmed, tested

#6002 Add built-in Picture-in-Picture button
  docs/guides/components.md
  docs/legacy-docs/guides/components.html
  package-lock.json
  package.json
  src/css/components/_picture-in-picture.scss
  src/css/video-js.scss
  src/js/control-bar/control-bar.js
  src/js/control-bar/picture-in-picture-toggle.js
  test/api/api.js
  test/unit/controls.test.js
Labels: tested

#6056 fix: undeprecate options()
  src/js/component.js
Labels: confirmed

#6062 fix: do not seek to live on first manual seek when autoplaying a live stream
  src/js/live-tracker.js
  test/unit/live-tracker.test.js
Labels: confirmed, tested

#6064 refactor(pip): rely only on WICG spec events
  src/js/control-bar/picture-in-picture-toggle.js
  src/js/player.js
  test/unit/controls.test.js
Labels: confirmed, tested
