Repository videojs/video.js, pull requests merged in 2019-03, with the labels that each got.

#5806 fix: changes max height of menus based on responsive classes.
  src/css/components/menu/_menu-popup.scss
Labels: confirmed, tested

#5822 fix: if play is delayed till loadstart, call load
  src/js/player.js
  test/unit/tech/tech-faker.js
Labels: tested

#5829 [i18n]Update Occitan language
  lang/oc.json
Labels: confirmed

#5831 fix warning - element supplied is not included in the DOM
  src/js/video.js
Labels: confirmed, tested

#5830 Fix Fullscreen Detection when Player is Nested within Document Fullscreen
  src/js/player.js
Labels: needs: testing

#5839 Fixes #5838. Ensure that controls exist prior to calling updateContent in resetProgressBar_
  package-lock.json
  src/js/player.js
  test/unit/reset-ui.test.js
Labels: confirmed, needs: testing

#5852 fix: Remove `playerEvent` and extra `timeupdate` handler in SeekBar
  src/js/control-bar/progress-control/seek-bar.js
Labels: confirmed

#5853 fix: trigger dispose on resize manager
  src/js/resize-manager.js
Labels: confirmed

#5860 fix: more memory leaks
  src/js/menu/menu.js
  src/js/player.js
  src/js/tech/tech.js
  src/js/tracks/html-track-element-list.js
  src/js/tracks/text-track.js
Labels: confirmed

#5857 Fix mute toggle
  src/js/control-bar/mute-toggle.js
Labels: confirmed, tested
