Repository videojs/video.js, pull requests merged in 2019-04, with the labels that each got.

#5914 fix: Always show the mute button by default in responsive mode.
  src/css/components/_adaptive.scss
Labels: confirmed

#5915 fix: Hide the progress control and show the subs-caps button when using Live UI at extra small size.
  src/css/components/_adaptive.scss
Labels: confirmed

#5929 fix: Explicitly remove all document-level listeners on player dispose.
  src/js/player.js
Labels: confirmed, patch

#5920 Fix typo in de translation
  lang/de.json
Labels: confirmed, patch

#5912 Add FullscreenApi pseudo-class for fullscreen then use in isFullscreen test
  src/js/fullscreen-api.js
  src/js/player.js
Labels: confirmed, patch

#5836 Fix bug preventing control bar from hiding on mobile
  src/js/player.js
Labels: confirmed, patch

#5895 fix: Correctly resolve play on middleware terminate
  src/js/player.js
  src/js/tech/middleware.js
  test/unit/autoplay.test.js
  test/unit/play.test.js
  test/unit/player.test.js
  test/unit/test-helpers.js
Labels: confirmed, patch, tested

#5863 Fix BPB announcement and operation on Chrome with JAWS screen reader
  src/js/player.js
  src/js/utils/browser.js
Labels: confirmed, minor
