Repository videojs/video.js, pull requests merged in 2019-08, with the labels that each got.

#6065 fix(lang): add Spanish translations
  docs/translations-needed.md
  lang/es.json
Labels: confirmed, patch

#6103 perf: Use weakmap for dom data
  src/js/component.js
  src/js/utils/dom-data.js
  src/js/utils/events.js
  test/unit/component.test.js
  test/unit/menu.test.js
  test/unit/utils/dom-data.test.js
  test/unit/videojs-integration.test.js
Labels: confirmed, minor, tested

#6148 perf: Improve performance of toTitleCase, register with lower and tit…
  src/js/component.js
  src/js/control-bar/text-track-controls/chapters-button.js
  src/js/control-bar/text-track-controls/subs-caps-button.js
  src/js/menu/menu-button.js
  src/js/player.js
  src/js/tech/html5.js
  src/js/tech/loader.js
  src/js/tech/middleware.js
  src/js/tech/tech.js
  src/js/utils/string-cases.js
  test/unit/utils/string-cases.test.js
Labels: confirmed

#6149 fix(lang): Add missing strings for Chinese (Simplified) and Chinese (Traditional)
  docs/translations-needed.md
  lang/zh-CN.json
  lang/zh-TW.json
  package.json
Labels: confirmed

#6046 'Esc' works for a vertical volume bar and menus
  src/css/components/_volume.scss
  src/css/components/menu/_menu-popup.scss
  src/js/clickable-component.js
  src/js/control-bar/volume-panel.js
  src/js/menu/menu-button.js
Labels: patch, tested

#6185 feat: allow player dimension method to accept 'auto'
  src/js/player.js
Labels: confirmed, minor

#6177 feat(middleware): allow middleware to handle muted setter/getter
  docs/guides/middleware.md
  src/js/tech/middleware.js
  test/unit/player.test.js
Labels: confirmed, minor

#6145 perf: Another 5ms of startup time improvements
  package-lock.json
  package.json
  rollup.config.js
  src/js/error-display.js
  src/js/tech/html5.js
  src/js/tracks/track-types.js
  src/js/utils/define-lazy-property.js
  src/js/utils/dom.js
  src/js/utils/events.js
  src/js/video.js
Labels: confirmed, minor

#6140 feat: Allow click handler to be specified in clickable component's options
  docs/guides/components.md
  src/js/clickable-component.js
  test/unit/clickable-component.test.js
Labels: minor

#6155 perf: only update ui on change, wrap things in requestAnimationFrame
  src/js/control-bar/progress-control/load-progress-bar.js
  src/js/control-bar/progress-control/progress-control.js
  src/js/control-bar/progress-control/seek-bar.js
  src/js/control-bar/time-controls/current-time-display.js
  src/js/control-bar/time-controls/duration-display.js
  src/js/control-bar/time-controls/remaining-time-display.js
  src/js/control-bar/time-controls/time-display.js
  src/js/slider/slider.js
  src/js/utils/clamp.js
  test/unit/tech/tech-faker.js
Labels: minor

#6192 fix: cap log history at 1000 items
  src/js/utils/create-logger.js
  test/unit/utils/log.test.js
Labels: confirmed, minor

#6099 feat: add isDisposed method to components
  docs/guides/player-workflows.md
  src/js/component.js
  test/unit/component.test.js
Labels: confirmed, minor

#6164 perf: Save 3740 bytes gizpped by getting rid of xhr deps
  package-lock.json
  package.json
  rollup.config.js
  src/js/extend.js
  src/js/tracks/text-track.js
  src/js/video.js
Labels: minor

#5649 chore: package json cleanup
  build/assets.js
  build/current-changelog.js
  build/docs-only.js
  build/fix-api-docs.js
  build/generate-example.js
  build/gh-release.js
  build/minify.js
  build/netlify-docs.js
  build/sandbox.js
  build/test-a11y.js
  build/translations.js
  build/version.js
  docs/translations-needed.md
  package-lock.json
  package.json
  rollup.config.js
  test/karma.conf.js
Labels: chore, patch

#5601 test: slight refactor to support rollup
  build/sandbox.js
  package-lock.json
  package.json
  rollup.config.js
  src/js/utils/url.js
  test/globals-shim.js
  test/karma.conf.js
  test/unit/component.test.js
  test/unit/player.test.js
  test/unit/poster.test.js
  test/unit/tech/html5.test.js
  test/unit/tracks/text-track-display.test.js
  test/unit/tracks/text-track.test.js
  test/unit/tracks/text-tracks.test.js
  test/unit/utils/url.test.js
  test/unit/video.test.js
  test/unit/videojs-integration.test.js
Labels: chore, patch
