Repository videojs/video.js, pull requests merged in 2019-11, with the labels that each got.

#6043 Load text tracks on demand
  docs/guides/options.md
  src/js/tech/tech.js
  src/js/tracks/text-track.js
Labels: minor

#6287 Chore: introduces core ES module.
  .gitignore
  .npmignore
  package.json
  rollup.config.js
Labels: needs: LGTM

#6249 feat: resets pastSeekEnd_ variable.
  src/js/live-tracker.js
  test/unit/live-tracker.test.js
Labels: needs: LGTM

#6319 Fix: Add detection to for iPadOS in IS_IPAD const
  src/js/utils/browser.js
Labels: tested

#6318 fix: encrypted content goes black in IE/Edge when video element focused
  src/js/big-play-button.js
Labels: Affects: a11y, tested
