Repository videojs/video.js, pull requests merged in 2021-03, with the labels that each got.

#7094 fix: add display block to all buttons icon placeholder
  src/css/components/_control.scss
Labels: needs: LGTM

#7021 fix: do not preload default text track if preloadTextTracks is false
  src/js/tracks/text-track.js
  test/unit/tracks/text-track.test.js
Labels: needs: LGTM

#7134 Add a player option `noUITitleAttributes` to prevent title attributes in the UI (fixes #6767).
  docs/guides/options.md
  docs/translations-needed.md
  index.html
  sandbox/noUITitleAttributes.html.example
  src/js/clickable-component.js
Labels: Affects: a11y

#7038 feat: Retry on error
  src/js/player.js
  test/unit/player.test.js
Labels: confirmed

#7098 feat: enable responsive controls on fullscreen
  src/css/components/_adaptive.scss
Labels: confirmed

#6824 Add volume tooltip
  src/css/components/_volume.scss
  src/js/control-bar/volume-control/mouse-volume-level-display.js
  src/js/control-bar/volume-control/volume-bar.js
  src/js/control-bar/volume-control/volume-control.js
  src/js/control-bar/volume-control/volume-level-tooltip.js
Labels: needs: updates

#7060 perf: wrap prototype methods in handlers in an arrow function
  src/js/big-play-button.js
  src/js/clickable-component.js
  src/js/control-bar/fullscreen-toggle.js
  src/js/control-bar/live-display.js
  src/js/control-bar/mute-toggle.js
  src/js/control-bar/picture-in-picture-toggle.js
  src/js/control-bar/play-toggle.js
  src/js/control-bar/playback-rate-menu/playback-rate-menu-button.js
  src/js/control-bar/playback-rate-menu/playback-rate-menu-item.js
  src/js/control-bar/progress-control/load-progress-bar.js
  src/js/control-bar/progress-control/progress-control.js
  src/js/control-bar/progress-control/seek-bar.js
  src/js/control-bar/seek-to-live.js
  src/js/control-bar/time-controls/duration-display.js
  src/js/control-bar/time-controls/remaining-time-display.js
  src/js/control-bar/time-controls/time-display.js
  src/js/control-bar/volume-control/volume-bar.js
  src/js/control-bar/volume-control/volume-control.js
  src/js/control-bar/volume-panel.js
  src/js/error-display.js
  src/js/live-tracker.js
  src/js/menu/menu-button.js
  src/js/menu/menu.js
  src/js/modal-dialog.js
  src/js/player.js
  src/js/plugin.js
  src/js/poster-image.js
  src/js/slider/slider.js
  src/js/tech/tech.js
  src/js/tracks/text-track-display.js
  src/js/tracks/text-track-settings.js
Labels: confirmed
