Repository videojs/video.js, pull requests merged in 2022-07, with the labels that each got.

#7788 feat: add a new title bar component
  index.html
  sandbox/index.html.example
  sandbox/load-media.html.example
  src/css/components/_big-play.scss
  src/css/components/_title-bar.scss
  src/css/video-js.scss
  src/js/player.js
  src/js/title-bar.js
  test/unit/title-bar.test.js
Labels: major

#7852 feat: Remove references and logic related to Flash and SWF
  sandbox/noUITitleAttributes.html.example
  src/css/components/_layout.scss
  src/js/player.js
  src/js/tech/setup-sourceset.js
  src/js/tech/tech.js
  src/js/utils/url.js
  test/unit/player.test.js
  test/unit/sourceset.test.js
Labels: major, 8.x

#7848 fix(lang): fixes key spacing within fr.json file
  lang/fr.json
Labels: patch

#7821 fix(lang): Update Polish language
  lang/pl.json
Labels: patch
