Repository videojs/video.js, pull requests merged in 2022-05, with the labels that each got.

#7692 fix: tight controlbar coupling (#7689)
  src/js/player.js
  test/unit/player.test.js
Labels: confirmed, patch

#7717 feat: export more helpers in videojs object
  src/js/video.js
Labels: needs: LGTM, major, bc-hack-week

#7735 chore: Update issue template to a form
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/config.yml
Labels: confirmed

#7707 feat: remove use of firstplay event
  src/js/player.js
  test/unit/player.test.js
Labels: major, bc-hack-week

#7694 docs: fix typo in components.html
  docs/legacy-docs/guides/components.html
Labels: confirmed, patch

#7697 docs(readme): updating the number of websites
  README.md
Labels: confirmed, patch

#7719 revert: Revert #7067 so we throw an error for invalid event types
  src/js/mixins/evented.js
  test/unit/mixins/evented.test.js
Labels: major, bc-hack-week

#7715 refactor: Remove workarounds for platforms without native promise support
  src/js/player.js
  src/js/tech/tech.js
  test/unit/utils/promise.test.js
Labels: major, bc-hack-week

#7701 chore: Remove IE-specific code
  src/js/big-play-button.js
  src/js/live-tracker.js
  src/js/player.js
  src/js/poster-image.js
  test/unit/tracks/text-tracks.test.js
  test/unit/utils/log.test.js
Labels: major, bc-hack-week

#7722 feat: Player can be replaced with original el after dispose()
  src/js/component.js
  src/js/player.js
  src/js/video.js
  test/unit/component.test.js
  test/unit/player.test.js
  test/unit/video.test.js
Labels: confirmed, minor

#7740 lang: Improving Russian translation
  docs/translations-needed.md
  lang/ru.json
Labels: confirmed, patch

#7745 feat(lang): add Estonian (et) translations
  lang/et.json
Labels: confirmed, minor

#7754 fix(accessibility): frame must have a title attribute
  lang/en.json
  src/js/resize-manager.js
Labels: confirmed, patch

#7776 fix: error message should not be localized in the player class
  src/js/player.js
Labels: patch

#7778 fix: HTML5 tech with audio tag shouldn't use requestVideoFrameCallback
  src/js/tech/html5.js
  test/unit/tech/html5.test.js
Labels: patch
