Repository videojs/video.js, pull requests merged in 2024-08, with the labels that each got.

#8790 chore: Remove safe-json-parse
  package.json
  src/js/player.js
  test/unit/setup.test.js
  test/unit/tracks/text-track-settings.test.js
Labels: patch

#8811 fix(types): Add has|usingPlugin to typedef by adding stubs which are removed from builds
  build/rollup-exclude-lines.js
  package.json
  rollup.config.js
  src/js/component.js
  src/js/player.js
Labels: confirmed

#8837 docs: Refresh README.md and point other docs to admin repo
  CODE_OF_CONDUCT.md
  COLLABORATOR_GUIDE.md
  CONTRIBUTING.md
  README.md
Labels: needs: LGTM
